CREATE DATABASE customer_behaviour;

USE customer_behaviour;

CREATE TABLE customer_data (
    customer_id              INT PRIMARY KEY,
    age                      INT,
    gender                   VARCHAR(20),
    item_purchased           VARCHAR(255),
    category                 VARCHAR(100),
    purchase_amount_usd      DECIMAL(10,2),
    location                 VARCHAR(255),
    size                     VARCHAR(50),
    color                    VARCHAR(50),
    season                   VARCHAR(50),
    review_rating            DECIMAL(3,2),
    subscription_status      VARCHAR(50),
    shipping_type            VARCHAR(100),
    discount_applied         VARCHAR(10),
    previous_purchases       INT,
    payment_method           VARCHAR(100),
    frequency_of_purchases   INT,
    age_group                VARCHAR(50),
    purchase_frequency_days  INT
);

ALTER TABLE customer_data
MODIFY COLUMN frequency_of_purchases VARCHAR(20);

SELECT COUNT(*)
FROM customer_data;

SELECT *
FROM customer_data
LIMIT 20;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount_usd) AS revenue
FROM customer_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, 
    purchase_amount_usd
FROM customer_data
WHERE discount_applied = 'Yes' 
  AND purchase_amount_usd >= (
        SELECT AVG(purchase_amount_usd) 
        FROM customer_data
  );

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS Average_Product_Rating
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase_amount
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount_usd), 2) AS avg_spend,
    ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_data
)
SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer_data
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_counts
)
SELECT 
    item_rank,
    category, 
    item_purchased, 
    total_orders
FROM ranked_items
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount_usd) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q11. Which products have more than 50 purchases?

SELECT 
    item_purchased,
    COUNT(*) AS total_orders
FROM customer_data
GROUP BY item_purchased
HAVING COUNT(*) > 50;
